"""Remove temporary column from Restaurant

Revision ID: 0f44719c3fb1
Revises: 92f8ce59fa62
Create Date: 2024-06-30 22:16:33.428945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f44719c3fb1'
down_revision = '92f8ce59fa62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('temporary_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_column', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
