"""almost

Revision ID: 327152ab42e8
Revises: d980e7962e90
Create Date: 2024-06-30 22:36:28.891397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327152ab42e8'
down_revision = 'd980e7962e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('extra_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_info', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
