"""Remove temporary column from Restaurant

Revision ID: 8be61ccf6b07
Revises: ed88015e9bd5
Create Date: 2024-06-30 22:04:40.942058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be61ccf6b07'
down_revision = 'ed88015e9bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('temporary_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_column', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
