"""Add temporary column to Restaurant

Revision ID: 92f8ce59fa62
Revises: 8be61ccf6b07
Create Date: 2024-06-30 22:15:37.008091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f8ce59fa62'
down_revision = '8be61ccf6b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_column', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('temporary_column')

    # ### end Alembic commands ###
