"""Added extra_info column to Restaurant model

Revision ID: d980e7962e90
Revises: 0f44719c3fb1
Create Date: 2024-06-30 22:33:30.655435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd980e7962e90'
down_revision = '0f44719c3fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_info', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('extra_info')

    # ### end Alembic commands ###
