"""Add temporary column to Restaurant

Revision ID: ed88015e9bd5
Revises: e7ab4a9c4d9b
Create Date: 2024-06-30 22:03:40.956923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed88015e9bd5'
down_revision = 'e7ab4a9c4d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_column', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('temporary_column')

    # ### end Alembic commands ###
